name: titan-infrastructure

services:
  # --- BANCO DE DADOS (Source of Truth) ---
  postgres:
    image: postgres:15-alpine
    container_name: titan_db
    environment:
      POSTGRES_USER: titan_user
      POSTGRES_PASSWORD: titan_password
      POSTGRES_DB: titan_ledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - titan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U titan_user -d titan_ledger"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- CACHE & LOCKING DISTRIBU√çDO ---
  redis:
    image: redis:7-alpine
    container_name: titan_redis
    ports:
      - "6379:6379"
    networks:
      - titan-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- OBSERVABILITY (NOVO) ---
  zipkin:
    image: openzipkin/zipkin
    container_name: titan_zipkin
    ports:
      - "9411:9411"
    networks:
      - titan-network

  # --- MESSAGE BROKER (KAFKA) ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: titan_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - titan-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  # --- UI PARA O KAFKA ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: titan_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - titan-network

volumes:
  postgres_data:

networks:
  titan-network:
    driver: bridge