name: titan-infrastructure

services:

  ledger-core:
    build: ./../../services/titan-ledger-core # Constrói a imagem a partir do diretório atual
    container_name: titan_ledger_core
    ports:
      - "8081:8081" # Expõe pra você acessar o Swagger
    environment:
      # Agora usamos os nomes dos containers, não localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/titan_ledger
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - titan-network
  # --- BANCO DE DADOS (Source of Truth) ---
  postgres:
    image: postgres:15-alpine
    container_name: titan_db
    environment:
      POSTGRES_USER: titan_user
      POSTGRES_PASSWORD: titan_password
      POSTGRES_DB: titan_ledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - titan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U titan_user -d titan_ledger"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- CACHE & LOCKING DISTRIBUÍDO ---
  redis:
    image: redis:7-alpine
    container_name: titan_redis
    ports:
      - "6379:6379"
    networks:
      - titan-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- MESSAGE BROKER (KAFKA) ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: titan_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - titan-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  # --- UI PARA O KAFKA ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: titan_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - titan-network
    # --- OBSERVABILITY ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: titan_jaeger
    ports:
      - "16686:16686" # UI (Acesse em http://localhost:16686)
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - titan-network
  # --- METRICS (PROMETHEUS) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: titan_prometheus
    ports:
      - "9090:9090"
    volumes:
      # Vamos criar esse arquivo no Passo 2
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite acessar o Java rodando fora do Docker
    networks:
      - titan-network

  # --- VISUALIZATION (GRAFANA) ---
  grafana:
    image: grafana/grafana:latest
    container_name: titan_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão
    depends_on:
      - prometheus
      - jaeger
    networks:
      - titan-network

volumes:
  postgres_data:

networks:
  titan-network:
    driver: bridge